site:
  full_name: SB
  short_name: Silvestar BistroviÄ‡
  description: Home of Silvestar BistroviÄ‡â€”fearless web engineer, CSS developer, JAMstack enthusiast, and WordPress theme specialist.
  logo: /gfx/svg/logo.svg
  logo_footer: /gfx/svg/logo-footer.svg
  language: en-US

home_page:
  - section:
    position: alpha
    title: Silvestar BistroviÄ‡
    id: Profile
    profile: https://res.cloudinary.com/starbist/image/upload/v1545137170/profile_tsqb7d.png
    profilealt: Headshot of myself, Silvestar BistroviÄ‡
    headings:
     - Fearless web engineer
     - CSS developer
     - JAMstack enthusiast
     - WordPress theme specialist
    list_class: beta
  - section:
    position: beta
    title: Featured Articles
    id: FeaturedArticles
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1565248044/My_favorite_Netlify_features-2x_inepie.jpg
        title: 'My favorite Netlify features'
        alt: 'Cover image with custom graphics for article My favorite Netlify features.'
        href: /articles/my-favorite-netlify-features/
      - src: https://res.cloudinary.com/starbist/image/upload/v1548013279/Introducing_Starter_Project_CLI-2x_gzuhpi.jpg
        title: 'Introducing SPRO'
        alt: 'Cover image with custom graphics for article Introducing SPRO.'
        href: /articles/introducing-spro/
      - src: https://res.cloudinary.com/starbist/image/upload/v1544203449/Building_an_animated_sticky_header_with_custom_offset_pnzuri.jpg
        title: 'Building an Animated Sticky Header With Custom Offset'
        alt: 'Cover image with custom graphics for article Building an Animated Sticky Header With Custom Offset.'
        href: /articles/building-an-animated-sticky-header-with-custom-offset/
      - src: https://res.cloudinary.com/starbist/image/upload/v1565249712/Alpha_Beta_Gamma_naming_convention-2x_jkluc6.jpg
        title: 'Alpha, Beta, Gamma naming convention'
        alt: 'Cover image with custom graphics for article Alpha, Beta, Gamma naming convention.'
        href: /articles/alpha-beta-gamma-naming-convention/
    links:
      See all articles â†’: /categories/articles/
  - section:
    position: gamma
    title: Portfolio
    id: Portfolio
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1573824300/cci_ohuha5.png
        title: "Credit Card Insider: A consumer education company"
        alt: Credit Card Insider website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/creditcardinsider/
      - src: https://res.cloudinary.com/starbist/image/upload/v1549951653/ddl_mypfrt.png
        title: "Domino Data Lab: A data science platform"
        alt: Domino Data Lab website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/dominodatalab/
      - src: https://res.cloudinary.com/starbist/image/upload/v1533798343/ww_hceizq.png
        title: "Westwing: A curated shoppable magazine"
        alt: Westwing website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/westwing/
      - src: https://res.cloudinary.com/starbist/image/upload/v1533798334/b_csao4p.png
        title: "Bozzuto: A diversified real estate company"
        alt: Bozzuto website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/bozzuto/
    links:
      See all projects â†’: /portfolio/
  - section:
    position: delta
    title: Publications
    id: Publications
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1565248200/css-tricks.com_my-favorite-netlify-features_vtsz7u.png
        title: "CSS Tricks: My favorite Netlify features"
        alt: "Screenshot of an article from CSS Tricks"
        href: https://css-tricks.com/my-favorite-netlify-features/
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668111/css-tricks-triangular-breadcrumb_wtapyn.jpg
        title: "CSS Tricks: Oh, the Many Ways to Make Triangular Breadcrumb Ribbons!"
        alt: "Screenshot of an article from CSS Tricks"
        href: https://css-tricks.com/oh-the-many-ways-to-make-triangular-breadcrumb-ribbons/
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668111/logrocket-css-style-guide_ca7glk.jpg
        title: "LogRocket blog: 5 things to consider when creating your CSS style guide"
        alt: "Screenshot of an article from LogRocket"
        href: https://blog.logrocket.com/5-things-to-consider-when-creating-your-css-style-guide-7b85fa70039d
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668110/toptal-ssg-overview_yo8dcs.jpg
        title: "Toptal blog: Overview of Popular Static Site Generators"
        alt: "Screenshot of an article from Toptal"
        href: https://www.toptal.com/front-end/static-site-generators-comparison-2018
      # - src: https://res.cloudinary.com/starbist/image/upload/v1557668111/toptal-ssg-wordpress_ktajsm.jpg
      #   title: "Toptal blog: A Guide to Static Site Generators Using Hexo and WordPress"
      #   alt: "Screenshot of an article from Toptal"
      #   href: https://www.toptal.com/front-end/wordpress-to-html-with-hexo-blog
  - section:
    position: epsilon
    title: Projects
    id: Projects
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1568017090/cld.silvestar.codes_skl3ax.png
        title: "Code Line Daily: A line of code of the day"
        alt: "Screenshot of Code Line Daily website"
        href: /articles/announcing-code-line-daily/
      - src: https://res.cloudinary.com/starbist/image/upload/v1568017094/starter.silvestar.codes_bu58p1.png
        title: "Starter Project: Gulp based boilerplate"
        alt: "Screenshot of Starter Project website"
        href: /articles/custom-wordpress-theme-development-with-spro/
      - src: https://res.cloudinary.com/starbist/image/upload/v1568017091/hugo.silvestar.codes_xr8vrt.png
        title: "Making a website with Hugo: A course"
        alt: "Screenshot of Making a website with Hugo website"
        href: /articles/making-a-website-with-hugo/
      - src: https://res.cloudinary.com/starbist/image/upload/v1568017094/play.silvestar.codes_ribbon_mjt4yx.png
        title: "Playground: UI demos"
        alt: "Screenshot of Playground"
        href: /articles/oh-the-many-ways-to-make-triangular-breadcrumb-ribbons/
  - section:
    position: omega
    list_class: omega
    title: Testimonials
    id: Testimonials
    quotes:
      - person: John Ganotis
        position: Entrepreneur
        project:
          name: Credit Card Insider
          link: /portfolio/creditcardinsider/
        paragraphs:
          - Silvestar is amazing. He is fast, and the work he produces is among the highest quality work I've seen from front-end engineers.
          - In our time working together he's been extremely reliable, with quick daily calls to give progress updates, but also having flexibility to work independently and provide updates on his progress on days when we skip those calls.
          - When working with Silvestar, I know that the work will be done quickly and correctly, but that he'll also point out any areas where he thinks we can improve. He's always looking out for opportunities to improve performance, maintainability, and accessibility. I get the impression that he's constantly learning and reflecting on his work, always looking for ways that he can build his skillset even more and produce even higher quality work (if that's possible!).
      - person: Evan Lavidor
        position: Partner & Executive Director
        project:
          name: BEAM Interactive
          link: /portfolio/bozzuto/
        paragraphs:
          - We've worked with Silvestar on several projects, and he's been a pleasure to work with on all of them. Recently, he handled primary front end development for two large web sites that were launched on Adobe Experience Manager. He's also worked on the front end development of a large WordPress project as well as some smaller campaign landing page and microsite work.
          - In all cases, Silvestar's been a breeze to work with. Communication is easy, and he's happy to be part of a larger team, attend regular standups, stay in close communication electronically, etc. (a key factor when working across countries/time zones).
          - His approach to front end development is modern, but he still knows how to debug for Internet Explorer and handle browser-specific issues. He's a thorough tester and has a great eye for detail.
          - Additionally, he's very fast. We were always impressed with the speed at which he could put things together at a very high level of quality.
          - I'd happily work with Silvestar again, and we'll definitely reach out to him in the future when we need help with additional projects.
      - person: Han Han Xue
        position: Product Designer
        project:
          name: Lyft
          link: /portfolio/hanhanxue/
        paragraphs:
          - I collaborated closely with Silvestar on a project.
          - Throughout the span of the project, Silvestar was able to consistently meet if not exceed expectations. He has the impressive ability to not only readily undertake direct requests, but also intuitively distill ambiguous asks in order to execute solves in a self-sufficient manner.
          - Silvestarâ€™s can-do attitude and palpable passion for the work combined with his extended knowledge makes for a highly effective problem solver who always strives to provide the best solutions.
          - If you aim for not only high standard in the result but also elegance in the process, then I would highly recommend considering Silvestar for your project."
      - person: Karim Mansi
        position: eCommerce Product Manager at Westwing Home & Living
        project:
          name: Westwing
          link: /portfolio/westwing/
        paragraphs:
          - While working a senior Product Manager at Westwing Home & Living, I had the pleasure to hire Silvestar to build our static corporate website. The project went very smoothly and was delivered on time. Communication with Silvestar was straightforward, clear and reliable. He was also very resourceful and what he didn't know he figured out on his own. I would definitely recommend him for static web solutions and other web front-end projects.

open_graph:
  pretty_url: true
  image: /gfx/jpg/cover.jpg
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: false
  items:
    Home: /
    Blog: /categories/articles/
    Portfolio: /portfolio/
    About: /about-me/
    My links: /links/
    Contact â†’: /contact/

portfolio:
  title: Projects
  items:
    Credit Card Insider: /portfolio/creditcardinsider/
    Calvert: /portfolio/calvert/
    Domino Data Lab: /portfolio/dominodatalab/
    Domino Data Lab Rev: /portfolio/dominodatalab-rev/
    Domino Data Lab Pop-up: /portfolio/dominodatalab-pop-up/
    Machine Learning Libraries: /portfolio/machine-learning-libraries/
    Westwing: /portfolio/westwing/
    Bozzuto: /portfolio/bozzuto/
    TheGrio: /portfolio/thegrio/
    Trase Yearbook 2018: /portfolio/yearbook-trase/
    Netki: /portfolio/netki/
    Contiamo: /portfolio/contiamo/
    Moodings: /portfolio/moodings/
    Han Han Xue: /portfolio/hanhanxue/
    Irina & Matej: /portfolio/irinaandmatej/

sidebar:
  title: Quick Links
  items:
    About: /about-me/
    Hire me: /hire-me/
    Services: /services/
    Contact: /contact/
    Mentoring: /mentoring/
    Setup: /uses/
    My Links: /links/
    CV: /portfolio/silvestar-bistrovic-cv.pdf
    # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: https://www.linkedin.com/in/starbist/
    GitHub: https://github.com/maliMirkec
    CodePen: https://codepen.io/CiTA/
    Twitter: https://twitter.com/malimirkeccita
    Silvestar BistroviÄ‡: /

banner1:
  span: "Got questions? Or projects? I would like to learn more. Contact me today!"
  btn1: "ðŸ‘‰ Get in touch"
  btn2: "2020 Q3-Q4"
  link: /contact/

banner2:
  span: "Got questions? Or projects? I would like to learn more. Contact me today!"
  btn1: "ðŸ‘‰ Get in touch"
  btn2: "2020 Q3-Q4"
  href: /contact/

widgets:
  cookies: true
  about:
    paragraphs:
      - I am Silvestar BistroviÄ‡â€”fearless web engineer, CSS developer, JAMstack enthusiast, and WordPress theme specialist.
    contact:
      Contact: /contact/
      # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: https://www.linkedin.com/in/starbist/
      GitHub: https://github.com/maliMirkec
      CodePen: https://codepen.io/CiTA/
      Twitter: https://twitter.com/malimirkeccita
  subnav:
    Silvestar BistroviÄ‡: /
    Contact: /contact/
    # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: https://www.linkedin.com/in/starbist/
    GitHub: https://github.com/maliMirkec
    CodePen: https://codepen.io/CiTA/
    Twitter: https://twitter.com/malimirkeccita
    Feed: https://www.silvestar.codes/rss2.xml
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestar.codes
    reddit: true
